In [36]:
import numpy as np
import pandas as pd
import math
from scipy import stats
import collections
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
import warnings
warnings.filterwarnings ("ignore")

In [37]:
filepath = 'C:/Users/dharmesh.kanzariya/Downloads/adult_csv.csv'

def loadData(filepath):
    
    adult_df = pd.read_csv(filepath)
    print(adult_df.shape)
    
    return adult_df


In [38]:
try:
    adult_df = loadData(filepath)
    #print(adult_df)
except:
    print("Error")

(48842, 15)


In [39]:
def dropCol (adult_df):
    
    adult_df.drop(['education', 'fnlwgt'], axis=1, inplace=True)
    print (adult_df.shape)
    print(adult_df)

    return adult_df

In [40]:
try:
    adult_df = dropCol(adult_df)
except:

    print("Error")
    print(adult_df.shape)

(48842, 13)
       age         workclass  education-num      marital-status  \
0        2         State-gov             13       Never-married   
1        3  Self-emp-not-inc             13  Married-civ-spouse   
2        2           Private              9            Divorced   
3        3           Private              7  Married-civ-spouse   
4        1           Private             13  Married-civ-spouse   
...    ...               ...            ...                 ...   
48837    2           Private             13            Divorced   
48838    4               NaN              9             Widowed   
48839    2           Private             13  Married-civ-spouse   
48840    2           Private             13            Divorced   
48841    1      Self-emp-inc             13  Married-civ-spouse   

              occupation    relationship                race     sex  \
0           Adm-clerical   Not-in-family               White    Male   
1        Exec-managerial         Husban

In [43]:
def treatNull(adult_df):
    
    null_counts = adult_df.isnull().sum()
    print(null_counts)
    
    unknown_count = (adult_df == '?').sum()
    print(unknown_count)
    
    adult_df = adult_df.replace('?', pd.NA)
    adult_df.fillna(adult_df.mode().iloc[0], inplace = True) 
    print(adult_df.info())
    
    return adult_df


In [44]:
try:
    adult_df = treatNull(adult_df)
    adult_df.head()
except:
    print(adult_df.shape)
    print("Error")
    

age                  0
workclass         2799
education-num        0
marital-status       0
occupation        2809
relationship         0
race                 0
sex                  0
capitalgain          0
capitalloss          0
hoursperweek         0
native-country     857
class                0
dtype: int64
age               0
workclass         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capitalgain       0
capitalloss       0
hoursperweek      0
native-country    0
class             0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             48842 non-null  int64 
 1   workclass       48842 non-null  object
 2   education-num   48842 non-null  int64 
 3   marital-status  48842 non-null  object
 4   occupation      48842 non-null  objec

In [46]:
def replaceTarget (adult_df):
    
    #Remove pass and write your logic here
    
    adult_df.head()
    adult_df['class'] = adult_df['class'].replace(['<=50K'], 0) 
    adult_df['class'] = adult_df['class'].replace(['>50K'], 1) 
    adult_df['class'] = adult_df['class'].astype('category')
    
    return adult_df


In [47]:
try:
  adult_df = replaceTarget(adult_df) 
  print (adult_df['class'])
except:
  print("Error")
  print(adult_df)

0        0
1        0
2        0
3        0
4        0
        ..
48837    0
48838    0
48839    0
48840    0
48841    1
Name: class, Length: 48842, dtype: category
Categories (2, int64): [0, 1]


In [53]:
def scaleDf (adult_df):
    
    #Remove pass and write your logic here
    #     scaled_df = adult_df.select_dtypes (include=np.number) 
#     scaled_column = adult_df.select_dtypes(include=['int64', 'float64'])
    scaled_column = adult_df.select_dtypes(include=[np.number]).columns
    print(scaled_column)
    # col = adult_df.select_dtypes (include = np.number).columns.tolist()
    mms = MinMaxScaler()
    scaled_value = mms.fit_transform(adult_df[scaled_column]) 
    scaled_df = pd.DataFrame(scaled_value, columns = scaled_column)
    print(scaled_df)
    return scaled_df


In [54]:
try:
    scaled_df = scaleDf(adult_df)
except:
    print("Error")
    print(scaled_df)

Index(['age', 'education-num', 'capitalgain', 'capitalloss', 'hoursperweek'], dtype='object')
        age  education-num  capitalgain  capitalloss  hoursperweek
0      0.50       0.800000         0.25          0.0          0.50
1      0.75       0.800000         0.00          0.0          0.00
2      0.50       0.533333         0.00          0.0          0.50
3      0.75       0.400000         0.00          0.0          0.50
4      0.25       0.800000         0.00          0.0          0.50
...     ...            ...          ...          ...           ...
48837  0.50       0.800000         0.00          0.0          0.50
48838  1.00       0.533333         0.00          0.0          0.50
48839  0.50       0.800000         0.00          0.0          0.75
48840  0.50       0.800000         0.50          0.0          0.50
48841  0.25       0.800000         0.00          0.0          0.75

[48842 rows x 5 columns]


In [57]:
def encodeDf (adult_df):
  # Remove pass and write your logic here
#     column_list = adult_df.columns.difference(['income'])

  # adult df adult df.:oc

  # col cat
  # adult df.columns.values.tolist()


  # print(col cat)
  # col cat col cat.remove("income")
  #print (encoded df.shape)
  #print(column List)
    categotical_columns = adult_df.select_dtypes(include=['category', 'object']).drop(columns='income').columns
    one_hot_encoded_data = pd.get_dummies (adult_df, columns = categotical_columns) 
#   print (encoded_df.shape)
    print (one_hot_encoded_data.shape)
    return one_hot_encoded_data

In [56]:
try:
  encoded_df = encodeDf(adult_df)
  print(encoded_df)
except:
  
  print("Error")

(48842, 121)
       age_0  age_1  age_2  age_3  age_4  capitalgain_0  capitalgain_1  \
0          0      0      1      0      0              0              1   
1          0      0      0      1      0              1              0   
2          0      0      1      0      0              1              0   
3          0      0      0      1      0              1              0   
4          0      1      0      0      0              1              0   
...      ...    ...    ...    ...    ...            ...            ...   
48837      0      0      1      0      0              1              0   
48838      0      0      0      0      1              1              0   
48839      0      0      1      0      0              1              0   
48840      0      0      1      0      0              0              0   
48841      0      1      0      0      0              1              0   

       capitalgain_2  capitalgain_3  capitalgain_4  ...  sex_Female  sex_Male  \
0                

In [61]:
def processedDf(encoded_df,scaled_df, adult_df): 
    adult_df_processed = pd.concat([encoded_df, scaled_df, adult_df['class']], axis=1)
    return adult_df_processed

In [62]:
try:
    adult_df_processed = processedDf (encoded_df, scaled_df, adult_df) 
    print(adult_df_processed.shape)
except:
    print(adult_df_processed.shape)
    print("Error")

(48842, 127)


In [65]:
def splitData(adult_df_processed):
    #Remove pass and write your logic here
    predictor = adult_df_processed.drop(columns='class')
    target = adult_df['class']
    # predictor = adult_df processed. loc[:, adult df processed. columns != 'income']
    # predictor = adult_df_processed
    X_train, X_test, y_train, y_test = train_test_split (predictor, target, test_size=0.25, random_state=40) 
    
    return X_train, y_train, X_test, y_test
  

In [67]:
try:
    X_train, y_train, X_test, y_test = splitData(adult_df_processed)
    print(X_train.shape, y_train.shape, X_test.shape, y_test.shape) 
except:
    print(X_train.shape, y_train.shape, X_test.shape, y_test.shape) 
    print("Error")

(36631, 126) (36631,) (12211, 126) (12211,)


In [69]:
def buildModel (X_train, y_train):
    #Remove pass and write your logic here
    # print(X train, shape, y train, shape)
    
    
    class_rf = RandomForestClassifier() 
    class_rf.fit(X_train, y_train)
    #print (X train.shape)
    return class_rf

In [70]:
try:
    train_model = buildModel (X_train, y_train)
except:
    print("Error")
    print(X_train.shape)

In [71]:
from sklearn.metrics import accuracy_score 

def evaluateModel (train_model,X_test,y_test): 
    test_score = train_model.score(X_test, y_test) 
#     acc = accuracy_score (y_test, y_pred)
    return test_score

In [72]:
try:
    score = evaluateModel (train_model,X_test,y_test) 
    print(score)
except:
    print(score)
    print("Error")


1.0


In [80]:
def create_matrix():
    #remove pass and write your logic here
    
    S= np.array([[-1, 1, 1, -1], [1, 1, -1, -1]])
    
    print(S)
    return S

In [81]:
try:
    S = create_matrix()
except:
    print('Error')


[[-1  1  1 -1]
 [ 1  1 -1 -1]]


In [82]:
def mat_scaling (S, scale=4):
  #remove pass and write your logic here 
    
    scaling_factor = np.sqrt(4)
    scaling_martix = np.array([[scaling_factor, 0], [0, scaling_factor]])
    
    S1 = np.dot(scaling_martix, S)
    
    return S1


In [84]:
try:
    scaled_matrix = mat_scaling(S)
    print(scaled_matrix)
except:
    print('Error')


[[-2.  2.  2. -2.]
 [ 2.  2. -2. -2.]]


In [92]:
from scipy.ndimage import rotate 
def mat_rotation(scaled_matrix, angle = 45): 
  #remove pass and write your logic here 
    
    angle = math.radians(45)
#     rotation = np.array([[math.cos(angle), -math.sin(angle)], [math.sin(angle), math.cos(angle)]])
    
    rotation = [[math.cos(math.pi/4), -math.sin(math.pi / 4)], [math.sin(math.pin / 4), math.cos(math.pi / 4)]]
    
    S11 = np.dot(rotation, scaled_matrix)
    # S45=rotate(scaled_matrix, angle) 
    print (S11)
    return S11

In [93]:
try:
    rotated_matrix = mat_rotation (scaled_matrix)
    print(rotated_matrix)
except:
    print(rotated_matrix)
    print('Error')

[[-2.82842712  0.          2.82842712  0.        ]
 [ 0.          2.82842712  0.         -2.82842712]]
Error


In [94]:
print("Rotated Matrix:",np.rot45(scaled_matrix))

AttributeError: module 'numpy' has no attribute 'rot45'

In [95]:
def createMatrix():
    
    #remove pass and write your logic here
    A= np.array([[3, 2, -1], [-2, 2, 1], [1,1,1]]) 
    B= np.array([6, 3, 4])
    return A, B


In [96]:
try:
  A,B = createMatrix()
  print (A)
except:
  print("Error")
  


[[ 3  2 -1]
 [-2  2  1]
 [ 1  1  1]]


In [97]:
def solveForxyz (A,B):
  #remove pass and write your logic here
  sol = np.linalg.solve(A, B)
  print (sol)
  x= int(sol[0])
  y= int(sol[1])
  z = int(sol[2])
  #return sol[0], sol[1], sol/21
  return x, y, z


In [98]:
try:
  x, y, z=solveForxyz (A, B) 
except:
  print('Error')


[1. 2. 1.]


In [99]:
def samplingSize():
 
  C12 = (0.01)**2
  size= ((1.96)**2 * (0.018) * (1- 0.018)) / (C12)
  # print(size)
  return(round (size))
 


In [100]:
try:
   sample_size = samplingSize() 
   print(sample_size)
except:
  print(sample_size)
  print("Error")

679


In [101]:
Samplesize = (((1.96 * 0.018)/(0.01)) ** 2)  
print(int(Samplesize))

12
