Data Science

In [1]:
import numpy as np
import pandas as pd
import math
from scipy import stats
import collections
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
import warnings
warnings.filterwarnings ("ignore")

In [1]:
filepath = 'C:/Users/dharmesh.kanzariya/Downloads/adult_csv.csv'

def loadData(filepath):
    '''
    adult_df = pd.read_csv(filepath)
    print(adult_df.shape)
    '''
    return adult_df


In [2]:
try:
    adult_df = loadData(filepath)
    print(adult_df)
except:
    print("Error")


Error


In [3]:
def dropCol (adult_df):
    '''
    adult_df = adult_df.drop(['education', 'fnlwgt'], axis=1)
    print (adult_df.shape)
    print(adult_df)
    '''
    return adult_df

In [5]:
try:
    adult_df = dropCol (adult_df)
except:
    print("Error")


Error


In [6]:
def treatNull(adult_df):
    '''
    print(adult_df.isnull())
    print(adult_df.isna().any())
    adult_df = adult_df.fillna(adult_df.mode().iloc[0]) 
    # print(adult_df.isnull())
    print(adult_df.info())
    '''
    
    return adult_df


In [7]:
try:
  adult_df = treatNull(adult_df)
  adult_df.head()
except:
  
  print("Error")
  print(adult_df)

Error


NameError: name 'adult_df' is not defined

In [8]:
def replaceTarget (adult_df):
    
    '''
    #Remove pass and write your logic here
    adult_df.head()
    adult_df['class'] = adult_df['class'].replace(['<=50K'], 0) 
    adult_df['class'] = adult_df['class'].replace(['>50K'], 1) 
    adult_df['class'] = adult_df['class'].astype('category')
    '''
  
    return adult_df


In [9]:
try:
  adult_df = replaceTarget(adult_df) 
  print (adult_df['class'])
except:
  print("Error")
  print(adult_df)

Error


NameError: name 'adult_df' is not defined

In [35]:
def scaleDf (adult_df):
  #Remove pass and write your logic here
  scaled_df = adult_df.select_dtypes (include=np.number) 
  col = adult_df.select_dtypes (include = np.number).columns.tolist()
  mms = MinMaxScaler()
  scaled_df[col] = mms.fit_transform(scaled_df[col]) 
  print(scaled_df)
  return scaled_df


In [36]:
try:
  scaled_df = scaleDf(adult_df)
except:
  print("Error")
  print(scaled_df)

        age  education-num  capitalgain  capitalloss  hoursperweek
0      0.50       0.800000         0.25          0.0          0.50
1      0.75       0.800000         0.00          0.0          0.00
2      0.50       0.533333         0.00          0.0          0.50
3      0.75       0.400000         0.00          0.0          0.50
4      0.25       0.800000         0.00          0.0          0.50
...     ...            ...          ...          ...           ...
48837  0.50       0.800000         0.00          0.0          0.50
48838  1.00       0.533333         0.00          0.0          0.50
48839  0.50       0.800000         0.00          0.0          0.75
48840  0.50       0.800000         0.50          0.0          0.50
48841  0.25       0.800000         0.00          0.0          0.75

[48842 rows x 5 columns]


In [42]:
def encodeDf (adult_df):
  # Remove pass and write your logic here
  column_list = adult_df.columns.difference(['income'])

  # adult df adult df.:oc

  # col cat
  # adult df.columns.values.tolist()


  # print(col cat)
  # col cat col cat.remove("income")
  #print (encoded df.shape)
  #print(column List)
  one_hot_encoded_data = pd.get_dummies (adult_df, columns = column_list) 
#   print (encoded_df.shape)
  print (one_hot_encoded_data.shape)
  return one_hot_encoded_data

In [44]:
try:
  encoded_df = encodeDf(adult_df)
  print(encoded_df)
except:
  
  print("Error")

(48842, 121)
       age_0  age_1  age_2  age_3  age_4  capitalgain_0  capitalgain_1  \
0          0      0      1      0      0              0              1   
1          0      0      0      1      0              1              0   
2          0      0      1      0      0              1              0   
3          0      0      0      1      0              1              0   
4          0      1      0      0      0              1              0   
...      ...    ...    ...    ...    ...            ...            ...   
48837      0      0      1      0      0              1              0   
48838      0      0      0      0      1              1              0   
48839      0      0      1      0      0              1              0   
48840      0      0      1      0      0              0              0   
48841      0      1      0      0      0              1              0   

       capitalgain_2  capitalgain_3  capitalgain_4  ...  sex_Female  sex_Male  \
0                

In [45]:
def processedDf(encoded_df,scaled_df, adult_df): 
  adult_df_processed = pd.concat([scaled_df, encoded_df], axis=1)
  return adult_df_processed

In [46]:
try:
  adult_df_processed = processedDf (encoded_df, scaled_df, adult_df) 
  print(adult_df_processed.shape)
except:
  print(adult_df_processed.shape)
  print("Error")

(48842, 126)


In [47]:
def splitData(adult_df_processed):
  #Remove pass and write your logic here
  target = adult_df['class']
  # predictor = adult_df processed. loc[:, adult df processed. columns != 'income']
  predictor = adult_df_processed
  X_train, X_test, y_train, y_test = train_test_split (predictor, target, test_size=0.25, random_state=40) 
  return X_train, y_train, X_test, y_test
  

In [48]:
try:
  X_train, y_train, X_test, y_test = splitData(adult_df_processed)
  print(X_train.shape, y_train.shape, X_test.shape, y_test.shape) 
except:
  print(X_train.shape, y_train.shape, X_test.shape, y_test.shape) 
  print("Error")

(36631, 126) (36631,) (12211, 126) (12211,)


In [49]:
def buildModel (X_train, y_train):
  #Remove pass and write your logic here
  # print(X train, shape, y train, shape)
  class_rf = RandomForestClassifier(random_state=0, max_depth=5) 
  class_rf.fit( X_train, y_train)
  #print (X train.shape)
  return class_rf

In [50]:
try:
  train_model = buildModel (X_train, y_train)
except:
  print("Error")
  print(X_train.shape)

In [51]:
from sklearn.metrics import accuracy_score 
def evaluateModel (train_model,X_test,y_test): 
  y_pred = train_model.predict(X_test) 
  acc = accuracy_score (y_test, y_pred)
  return acc

In [52]:
try:
  score = evaluateModel (train_model,X_test,y_test) 
  print(score)
except:
  print(score)
  print("Error")


1.0


In [58]:
def create_matrix():
  #remove pass and write your logic here
  S= [[-1, 1, 1, -1], [1, 1, -1, -1]] 
  print(S)
  return S

In [59]:
try:
  S = create_matrix()
except:
  print('Error')


[[-1, 1, 1, -1], [1, 1, -1, -1]]


In [60]:
def mat_scaling (S, scale=4):
  #remove pass and write your logic here 
  S4= np.multiply(S, scale)
  print (S4)
  return S4


In [61]:
try:
  scaled_matrix = mat_scaling(S)
except:
  print('Error')


[[-4  4  4 -4]
 [ 4  4 -4 -4]]


In [62]:
from scipy.ndimage import rotate 
def mat_rotation(scaled_matrix, angle = 45): 
  #remove pass and write your logic here 
  S45=rotate(scaled_matrix, angle) 
  print (S45)
  return S45

In [63]:
try:
  rotated_matrix = mat_rotation (scaled_matrix)
  # print(rotated_matrix)
except:
  print('Error')

[[ 0  0  0  0]
 [ 0  0 -1  0]
 [ 0  3  0  0]
 [ 0  0  0  0]]


In [65]:
print("Rotated Matrix:",np.rot45(scaled_matrix))

AttributeError: module 'numpy' has no attribute 'rot45'

In [49]:
def createMatrix():
  #remove pass and write your logic here
  A= np.array([[3, 2, -1], [-2, 2, 1], [1,1,1]]) 
  B= np.array([6, 3, 4])
  return A, B


In [50]:
try:
  A,B = createMatrix()
  print (A)
except:
  print("Error")
  


[[ 3  2 -1]
 [-2  2  1]
 [ 1  1  1]]


In [51]:
def solveForxyz (A,B):
  #remove pass and write your logic here
  sol = np.linalg.solve(A, B)
  print (sol)
  x= int(sol[0])
  y= int(sol[1])
  z = int(sol[2])
  #return sol[0], sol[1], sol/21
  return x, y, z


In [52]:
try:
  x, y, z=solveForxyz (A, B) 
except:
  print('Error')


[1. 2. 1.]


In [53]:
def samplingSize():
 
  C12 = (0.01)**2
  size= ((1.96)**2 * (0.018) * (1- 0.018)) / (C12)
  # print(size)
  return(round (size))
 


In [54]:
try:
   sample_size = samplingSize() 
   print(sample_size)
except:
  print(sample_size)
  print("Error")

679


In [57]:
Samplesize = (((1.96 * 0.018)/(0.01)) ** 2)  
print(int(Samplesize))

12
